import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'

// Components using document or window elements must deactivate ssr to be used on client side
// https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr
const ContentWithoutSSR = dynamic(async () => import('../components/content/Content'), {
  ssr: false
})

const Home: NextPage = () => {
  return (
    <div className="okp4-faucet-testnet-main">
      <Head>
        <title>OKP4 Faucet Testnet</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/okp4-logo.png" rel="icon" />
      </Head>

      <ContentWithoutSSR />
    </div>
  )
}

export default Home
