name: Follow contributor

on:
  pull_request:
    branches: [main]

jobs:
  follow-user:
    runs-on: ubuntu-22.04
    steps:
      - name: Follow user
        uses: okp4/follow-contributor-action@v1.1.0
        with:
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.OKP4_TOKEN }}
